#!/usr/bin/env bash
# Portable, idempotent ZAOS bootstrap. It never installs vendor software or secrets.
set -euo pipefail
ROOT=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd -P)
workspace=""
usage(){ echo 'usage: ./install.sh --workspace <directory>' >&2; }
while [ "$#" -gt 0 ]; do case "$1" in --workspace) workspace="${2:-}"; shift 2;; -h|--help) usage; exit 0;; *) usage; exit 64;; esac; done
[ -n "$workspace" ] || { usage; exit 64; }
mkdir -p "$workspace"
workspace=$(cd "$workspace" && pwd -P)
config_dir="${ZAOS_SHIM_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/zaos-native}"
mkdir -p "$config_dir"
cat > "$config_dir/config.sh" <<EOF
# Generated by ZAOS install. No secrets belong here.
ZAOS_AGENTS_ROOT="$ROOT"
ZAOS_WORKSPACE_ROOT="$workspace"
ZAOS_FRAMEWORK_VERSION="$(tr -d '[:space:]' < "$ROOT/VERSION")"
ZAOS_REAL_BIN_DIR="${ZAOS_REAL_BIN_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/zaos/real-bin}"
EOF
bin_dir="${ZAOS_SHIM_BIN_DIR:-$HOME/.local/bin}"
mkdir -p "$bin_dir"
if [ ! -e "$bin_dir/zaos" ] || [ "$(readlink -f "$bin_dir/zaos" 2>/dev/null || true)" = "$ROOT/engines/bin/zaos" ]; then
  ln -sfn "$ROOT/engines/bin/zaos" "$bin_dir/zaos"
else
  echo "WARN: existing $bin_dir/zaos was not changed; use $ROOT/engines/bin/zaos directly." >&2
fi
"$ROOT/engines/bin/zaos-install-native-shims" install
"$ROOT/engines/bin/zaos-engines" status
set +e
"$ROOT/engines/tools/zaos-doctor" --groups git --project "$ROOT"
doctor_rc=$?
set -e
[ "$doctor_rc" -lt 2 ] || { echo 'BLOCKED: ZAOS doctor could not verify installation.' >&2; exit "$doctor_rc"; }
echo "PASS: ZAOS installed for workspace $workspace"
